version: 2
jobs:
  build:
    branches:
      only:
        - master
        - /release-.*/
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: yarn
      - run: yarn test:unit
      - run: yarn test:e2e