# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@1.11.0
# workflows:
#   build:
#     branches:
#       only:
#         - master
#         - /release-.*/
#     jobs:
#       - cypress/run:
#         yarn: true

# jobs:
#   build:
#     branches:
#       only:
#         - master
#         - /release-.*/
#     docker:
#       - image: circleci/node:10.16.3
#     steps:
#       - checkout
#       - run: yarn
#       - run: yarn test:unit
#       - run: yarn test:e2e
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: yarn
  test_unit:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: yarn test:unit
  # test_e2e:
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_unit
