# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@1.11.0
# workflows:
#   build:
#     branches:
#       only:
#         - master
#         - /release-.*/
#     jobs:
#       - cypress/run:
#         yarn: true

# jobs:
#   build:
#     branches:
#       only:
#         - master
#         - /release-.*/
#     docker:
#       - image: circleci/node:10.16.3
#     steps:
#       - checkout
#       - run: yarn
#       - run: yarn test:unit
#       - run: yarn test:e2e
version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/node:10.16.3
jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run: yarn
  test_unit:
    executor: my-executor
    steps:
      - checkout
      - run: yarn test:unit
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test_unit:
          requires:
            - build
