version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  my-executor:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/erp
jobs:
  install:
    executor: my-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/erp
      - run: pwd
      - run: yarn
      - run: ls -a
      - persist_to_workspace:
          root: ~/erp
          paths:
            - ./node_modules
            - yarn.lock
  test_unit:
    executor: my-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/erp
      - run: pwd
      - run: ls -a
      - run: yarn test:unit
workflows:
  version: 2.1
  install_and_test:
    jobs:
      - install
      - test_unit:
          requires:
            - install
      - cypress/run:
          start: npm run serve
          wait-on: 'http://localhost:8080'
          executor: cypress/browsers-chrome69
          yarn: true
          browser: chrome
          requires:
            - install
          record: true
